on:
  pull_request:
    branches:
      - main

jobs:
  backend-build:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        # with:
        #   python-version: 3.9

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # - name: Run unit tests
      #   run: pytest

      - name: Run backend server
        run: python3 main.py

  frontend-build:
    needs: backend-build

    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        # with:
        #   node-version: 16

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci

      - name: Check lint error
        run: npm run lint

      - name: Run Playwright integration tests
        run: npm run test
