on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: windows-latest # or macos-latest, ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: npm ci

      - name: Check lint error
        run: npm lint

      - name: Run Playwright integration tests
        run: npm run test
